In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [2]:
df = pd.read_csv("AI_ValuePredictor_FinalDataset.csv")

In [3]:
X = df[[
    "Age",
    "Goals",
    "Assists",
    "xG",
    "xA",
    "PassAccuracy",
    "KeyPasses",
    "TacklesWon",
    "Interceptions",
    "DefensiveDuelsWon",
    "Shots",
    "ShotsOnTarget",
    "DribblesCompleted",
    "ProgressivePasses",
    "ProgressiveCarries",
    "GoalContribution",
    "PerformanceScore",
    "EfficiencyIndex"
]]

In [4]:
y = df["MarketValueEUR"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [7]:
y_pred = model.predict(X_test)

In [8]:
r2 = r2_score(y_test, y_pred)

mae = mean_absolute_error(y_test, y_pred)

print("R-squared :", round(r2,3))
print("MAE :", round(mae,2))

R-squared : 0.262
MAE : 17718905.83

In [9]:
comparison = pd.DataFrame({
    "Actual Value": y_test.values,
    "Predicted Value": y_pred
})

comparison.head(10)

   Actual Value  Predicted Value
0      33311000     4.996824e+07
1      75834000     4.880239e+07
2      94027000     4.377543e+07
3     109322000     8.586327e+07
4      15891000     1.921808e+07
5      82068000     5.355206e+07
6      86622000     4.673732e+07
7      30501000     1.566418e+07
8      11957000     2.261098e+07
9      27277000     1.761792e+07

In [10]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

importance.sort_values(by="Coefficient", ascending=False)

               Feature   Coefficient
16    PerformanceScore  3.153176e+06
10               Shots  3.274173e+05
4                   xA  2.974070e+05
12   DribblesCompleted  2.196292e+05
0                  Age  2.044082e+05
11       ShotsOnTarget -8.678715e+03
17     EfficiencyIndex -5.436278e+04
9    DefensiveDuelsWon -1.060907e+05
3                   xG -1.496037e+05
5         PassAccuracy -1.839682e+05
14  ProgressiveCarries -1.403373e+06
13   ProgressivePasses -1.462648e+06
7           TacklesWon -2.897691e+06
2              Assists -3.396671e+06
1                Goals -3.684406e+06
8        Interceptions -3.733124e+06
6            KeyPasses -5.063196e+06
15    GoalContribution -7.081077e+06

In [11]:
print(df.shape)

(8000, 19)

# Create a Predictions DataFrame

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [27]:
full_df = pd.read_csv("PlayerDashboard.csv")

In [28]:
full_df.head()

,PlayerID,PlayerName,Age,Height,Weight,PreferredFoot,Nationality,ClubName,LeagueName,LeagueCountry,...,TacklesWon,Interceptions,DefensiveDuelsWon,Shots,ShotsOnTarget,DribblesCompleted,ProgressivePasses,ProgressiveCarries,GoalValueRatio,PerformanceScore
0,8,Adama Garcia,28,188,72,Right,Denmark,Inter Wanderers,Primeira Coroa,Portugal,...,8.28,7.91,262.2,2.14,129.4,3.59,22.33,8.14,1.350000e-08,29.275
1,19,Adama Wilson,24,175,73,Right,Serbia,West Villans,Premier Division,France,...,8.30,8.86,281.9,4.02,164.3,2.83,15.37,8.54,1.860000e-08,28.196
2,21,Jordan Muller,21,179,63,Right,France,FC United FC,Premier Division,Germany,...,1.76,2.34,190.5,11.46,143.0,10.76,9.73,12.59,1.685250e-07,66.830
3,22,Nils Kovac,27,170,80,Right,Argentina,United CF,Premier Division,Spain,...,3.91,2.77,177.8,17.58,197.8,10.00,16.18,18.07,1.969200e-07,53.864
4,25,Mikkel Fernandez,33,171,68,Left,Poland,Inter City FC,Primeira Coroa,Portugal,...,3.60,2.37,192.9,13.10,188.9,14.29,13.70,14.81,1.925800e-07,60.026

In [29]:
features = [
    "Age",
    "Goals",
    "Assists",
    "xG",
    "xA",
    "PassAccuracy",
    "KeyPasses",
    "TacklesWon",
    "Interceptions",
    "DefensiveDuelsWon",
    "Shots",
    "ShotsOnTarget",
    "DribblesCompleted",
    "ProgressivePasses",
    "ProgressiveCarries",
    "GoalContribution",
    "PerformanceScore"
]

In [30]:
X = full_df[features]
y = full_df["MarketValueEUR"]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [33]:
y_pred = model.predict(X_test)

In [34]:
predictions = full_df.loc[y_test.index, ["PlayerName", "MarketValueEUR"]].copy()

In [35]:
predictions.rename(
    columns={"MarketValueEUR": "ActualMarketValue"},
    inplace=True
)

In [36]:
predictions["PredictedMarketValue"] = y_pred

In [37]:
predictions["ValueDifference"] = (
    predictions["PredictedMarketValue"]
    - predictions["ActualMarketValue"]
)

In [38]:
predictions.head()

          PlayerName  ActualMarketValue  PredictedMarketValue  ValueDifference
1860   Liam de Vries         52555400.0          4.043769e+07    -1.211771e+07
353    Marcus Garcia         27230000.0          2.333995e+07    -3.890055e+06
1333   Bruno Bianchi         90677000.0          5.764860e+07    -3.302840e+07
905       Kofi Kovac         17094000.0          4.691190e+07     2.981790e+07
1289  Antoine Jansen         23960250.0          2.820548e+07     4.245227e+06

# Find undervalued players

In [39]:
undervalued_players = predictions[
    predictions["PredictedMarketValue"] >
    predictions["ActualMarketValue"]
]

In [40]:
undervalued_players = undervalued_players.sort_values(
    by="ValueDifference",
    ascending=False
)

In [41]:
undervalued_players.head(10)

,PlayerName,ActualMarketValue,PredictedMarketValue,ValueDifference
712,Milos Romano,1.853850e+07,6.535811e+07,4.681961e+07
618,Antoine Carvalho,1.720400e+07,5.154493e+07,3.434093e+07
1872,Kevin Andersen,2.690975e+07,5.895319e+07,3.204344e+07
1905,Lucas Moreau,2.617500e+07,5.797649e+07,3.180149e+07
128,Kwame Nielsen,1.703200e+07,4.786573e+07,3.083373e+07
1930,Thiago Fischer,8.922400e+06,3.945078e+07,3.052838e+07
1798,Bruno Brown,2.032540e+07,5.022730e+07,2.990190e+07
905,Kofi Kovac,1.709400e+07,4.691190e+07,2.981790e+07
886,Ibrahim Romano,2.371433e+07,5.172663e+07,2.801230e+07
1675,Ethan Sousa,1.221500e+07,4.011722e+07,2.790222e+07

In [42]:
undervalued_players.to_csv(
    "UndervaluedPlayers.csv",
    index=False
)

print("File exported successfully!")

File exported successfully!